### ISSUE TITLE
[Bug]: Resource not accessible by integration

### ISSUE THREAD

**Issue by HsiangNianian** [vj-abigo/invite-on-label#35]
### Contact Details

HsiangNianian@outlook.com

### What is the Issue?

Hi,
When I got everything ready according to the tutorial, I encountered such an error.
![image](https://user-images.githubusercontent.com/44714368/219929569-b80a52cb-b57d-4317-af1a-43391e024ac2.png)
![image](https://user-images.githubusercontent.com/44714368/219931696-0ba262bb-e94e-4b73-a06b-0270b9d4de15.png)

### Version

1.4 (Default)

### Relevant log output (optional)

```shell
/home/runner/work/_actions/vj-abigo/invite-on-label/v1.4/dist/index.js:4868
        const error = new requestError.RequestError(message, status, {
                      ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/vj-abigo/invite-on-label/v1.4/dist/index.js:4868:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/work/_actions/vj-abigo/invite-on-label/v1.4/dist/index.js:65:7) {
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 19 Feb 2023 05:38:07 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-[11](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:12)-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '2802:80E1:2B68EE7:59A711C:63F1B5BF',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '860',
    'x-ratelimit-reset': '16767878[13](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:14)',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '[14](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:15)0',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/Diaries-Store/support/issues/5/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.2.4 Node.js/[16](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:17).16.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"You are already a member of our Organisation."}',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/Diaries-Store/support/actions/runs/4214782807/jobs/7315467220#step:2:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  },
  documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HsiangNianian** [comment]
I solved it through `permission: write-all` in CI.
